FROM ruby:3.4.3-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential \
            libyaml-dev \
            pkg-config \
            libssl-dev \
            curl \
            git
            
# Set working directory
WORKDIR /rails

#COPY Gemfile Gemfile.lock ./
COPY Gemfile* ./
RUN bundle install

RUN groupadd -r --gid 1000 rails && \
    useradd -m -r --uid 1000 --gid 1000 rails

USER rails

